packages:
  - apps/*
  - tooling/*

catalog:
  "prettier": ^3.6.2
  "typescript": ^5.9.3
  "@eslint/js": ^9.38.0
  "@types/node": ^22.18.12
  "eslint": ^9.38.0
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "tailwindcss": ^4.1.16

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss